### ISSUE TITLE
VirtualBox guest mouse integration

### ISSUE THREAD

**Issue by jgroenveld** [project-trident/trident-installer#11]
Installing Trident on a VBox guest, installer correctly detects VBox video, but the mouse integration is not working and must capture mouse.
John
groenveld@acm.org

**Comment by jgroenveld** [comment]
```
On reboot, mouse integration works correctly.
John
groenveld@acm.org
```

**Comment by beanpole135** [comment]
This is actually intentional:
The vboxguest module integration is already integrated into the ISO but it is disabled at the moment due to some issues with the window size that the module was reporting (it was a crazy-high resolution like 16k or something - made it unusable even on a couple 4K screens.

We are currently looking into a way to better detect a virtual environment (VBox, VMWare, etc...) and just set a hard resolution for the ISO those environments (something like 1366x768, not too big but not too small either).

**Comment by RodMyers** [comment]
can you try the RELEASE ISO?
