### ISSUE TITLE
Consider adding a symlink from /usr/local/share/trueos to /usr/local/share/trident

### ISSUE THREAD

**Issue by NorwegianRockCat** [project-trident/trident-installer#20]
This is more of a suggestion if there will ever be an upgrade path, but it's also low hanging fruit, so consider fixing it.

In older releases of TrueOS, new users got an .xprofile created for them that included a line something like:
```
if [ $i = "/usr/local/share/true/xstartup/enable-inputmethod.sh" ] || [ $i = "/usr/local/share/trueos/xstartup/gpg-agent.sh" ] || [ $i = "/usr/local/share/trueos/xstartup/ssh-agent.sh" ] 
```
That ran these nice system-wide scripts to enable gpg-agent and so on.

If a user just installs trident into a boot environment, this X configuration won't work since there is no longer a `/usr/local/share/trueos` but a `/user/local/share/trident`

Of course most users will only notice this when ssh-agent isn't working as they expect. Then they have to know that this was set up in .xprofile. It's not straightforward and it's not documented anywhere.

In the name of compatibility, I would suggest either:
1. Making a symlink from /usr/local/share/trident to /usr/local/share/trueos OR
2. Make a /usr/local/trueos directory and symlink the scripts from trident.

I suspect number 2 will work in more situations and "just work". You could also go one step further and do the same thing for PC-BSD, but I guess the number of upgrades from that will be low.

**Comment by beanpole135** [comment]
This should be fixed now without the use of a symlink:
Trident installs a little script called [setup-xorg-session](https://github.com/project-trident/trident-core/blob/master/core-files/usr/local/bin/setup-xorg-session) into "/usr/local/bin" and the sys-init script will automatically place running that script at the top of the ~/.xprofile file for all users if it does not already exist there (plus the template file for new users as well).

What this script does is basically look for any user-level xorg setup scripts in any "xstartup[-parallel]" directories in /etc, /usr/local/etc, or /usr/local/share/trident in order to setup the xorg session before the desktop/WM is launched.
This allow the user to add/remove any of their own user-session setup scripts as desired, as well as check the built-in ones that Project Trident installs out-of-box (which include the old ssh-agent and input method scripts from TrueOS).
