### ISSUE TITLE
Documentation: How to save an installation log?

### ISSUE THREAD

**Issue by allentiak** [project-trident/trident-installer#47]
(I couldn't find any documentation on the installer from which to get this info, nor any other place where to ask this question...)

**Comment by q5sys** [comment]
You should also be able to save it to a USB stick.  However since the ISO is limited in what is installed on it, you'd have to use a Fat32 drive.  Drop to the terminal and run:
`mkdir /media/usb`
`mount -t msdosfs -o -m=644,-M=755 /dev/da0s1 /media/usb`
`cp /tmp/install.log /media/usb/install.log`
You'll have to change the device path depending on what its recognized as on your computer.  Once you plug in the drive run `dmesg | tail` to see what the device path is.

**Comment by allentiak** [comment]
Thanks!
