### ISSUE TITLE
Graphical installer fails to launch with X error

### ISSUE THREAD

**Issue by kiltedkoder** [project-trident/trident-installer#51]
I used the "stable" ISO.  X crashes and the system sits there and does nothing.  After  an hour I then hit ctrl-c and it then told me the installation was complete.  Obviously it wasn't, but the ctrl-c ended the launch script so I guess it assumed things went well.
I have an Intel 7th gen CPU and an Nvidia RTX card. 
Most peculiarly, it worked A-Ok on my thinkpad with intel graphics and it worked A-Ok in virtualbox.

Possible nvidia bug?

**Comment by RodMyers** [comment]
BIOS or EFI?

**Comment by kiltedkoder** [comment]
idk.  EFI I guess since its a new system.  The ISO loads, I get a scrolling wall of FreeBSD stuff that makes no sense to me.  Im assuming that cause X is trying to launch, whichever of those im using is ok.
Is X dependent on EFI to load?  
BTW, thanks for the lightning fast response.  I dont think I've ever gotten a bug response so quick. :)

**Comment by RodMyers** [comment]
best bet is to use telegram, i just happened to catch the email.

dvd or USB for install media?

**Comment by beanpole135** [comment]
@kiltedkoder : FreeBSD has currently broken the "vesa" graphics driver which is the primary graphical support option for the installation on Legacy-boot systems right now. If you can switch to UEFI boot, it should be able to use the newer "scfb" driver to get you through the installation so that you can use the NVIDIA graphics post-install.
There is no nvidia driver installed on the ISO itself, due to the variety of conflicting versions available for the end-user, so during the installation you will need to pick the right version that will work for your card (defaults to the 390.x driver from NVIDIA, but the 304.x and 340.x drivers are also there).

**Comment by beanpole135** [comment]
This should be resolved now. The "vesa" graphics driver was fixed upstream in FreeBSD and is included in the latest Trident releases.
